version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DEBUG=0
      - PRODUCTION=1
      - DATABASE_URL=postgresql://rfobserver:rfobserver@database:5432/rfobserver
      - MAX_WORKERS=4

  database:
    restart: always
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-rfobserver}
      - POSTGRES_USER=${DB_USER:-rfobserver}
      - POSTGRES_DB=${DB_NAME:-rfobserver}

  nginx:
    volumes:
      - ./nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always 